// <auto-generated />
using System;
using Blogger.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogger.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3734eaa9-9ec4-4d7d-9489-2d79be9ed468"),
                            CategoryId = new Guid("8796b8a7-b7e6-4e55-b72e-7efcc8e8c3bc"),
                            Content = "Konu üzerine alıştırmalar",
                            CreatedBy = "AdminTest",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(490),
                            ImageId = new Guid("06227709-06de-407e-abd9-9a61b5281852"),
                            Title = "deneme1",
                            ViewCount = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8b6507f4-c057-4ba5-95b6-14b99f3cdbca"),
                            CategoryId = new Guid("21c3fc25-d3d5-4454-bede-4667d3ffb807"),
                            Content = "Konu üzerine alıştırmalar2",
                            CreatedBy = "AdminTest",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(494),
                            ImageId = new Guid("2b50160d-2f34-4b6b-bc3c-ee5fb76bfd0f"),
                            Title = "deneme2",
                            ViewCount = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("01e52e32-1321-4d63-a375-9f261d2959d9"),
                            CategoryId = new Guid("d0e722bd-834d-4e66-a2e2-2865d06e1281"),
                            Content = "Konu üzerine alıştırmalar3",
                            CreatedBy = "AdminTest",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(508),
                            ImageId = new Guid("bef41f71-3c3a-4c41-b256-bae6c5cae8dc"),
                            Title = "deneme3",
                            ViewCount = 1,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8796b8a7-b7e6-4e55-b72e-7efcc8e8c3bc"),
                            CategoryName = "Spor",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(678),
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("21c3fc25-d3d5-4454-bede-4667d3ffb807"),
                            CategoryName = "Sinema",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(681),
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d0e722bd-834d-4e66-a2e2-2865d06e1281"),
                            CategoryName = "Tiyatro",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(684),
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06227709-06de-407e-abd9-9a61b5281852"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(764),
                            FileName = "images/File1.jpg",
                            FileType = ".jpg",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("2b50160d-2f34-4b6b-bc3c-ee5fb76bfd0f"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(766),
                            FileName = "images/File12.jpg",
                            FileType = ".jpg",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bef41f71-3c3a-4c41-b256-bae6c5cae8dc"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 10, 15, 32, 15, 171, DateTimeKind.Local).AddTicks(769),
                            FileName = "images/File13.jpg",
                            FileType = ".jpg",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.HasOne("Blog.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
